language: go

sudo: false

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: always

go:
  - 1.6.3
  - 1.7.1

install:
  - go get github.com/Masterminds/glide
  - make get

script:
  - make
